spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.44:5432/courier-app
    username: postgres
    password: 1801
  security:
    user:
      password: 1801
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 2MB
  mvc:
    problemdetails:
      enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: true
#  endpoint:
#    env:
#      enabled: true
#    info:
#      enabled: true

logging:
  level:
    web: debug
    com.duberlyguarnizo.courierapp: trace
    org.springframework.security: trace
  pattern:
    console: "%clr(%d{dd/MM HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx" #add year for production!

custom:
  properties:
    jwtSecret: courierAppSecretKey #TODO: Get values from environment or external file
    jwtExpirationMs: 86400000
    jwtCookieName: courier-app
    remember:
      key: all_the_things_ive_done